### ISSUE TITLE
Error: directory that does not already exist!

### ISSUE THREAD

**Issue by Morteza1395** [NASA-DEVELOP/METRIC#6]
Hi
I cannot run METRIC "metric_tbx.pyt" , Error is:

"Traceback (most recent call last):
  File "<string>", line 249, in execute
  File "D:\METRIC-master\METRIC\prepare_metric_env.py", line 115, in prepare_metric_env
    raise Exception("input workspace must be a directory that does not already exist! one will be created here!")
Exception: input workspace must be a directory that does not already exist! one will be created here!

Failed to execute (METRIC_configure)."

I saw coment in "https://github.com/NASA-DEVELOP/METRIC/issues/5" and use "https://github.com/NASA-DEVELOP/METRIC/archive/patch-ovr-issue.zip" file but I faced by error message again, How do I Solve It?
best regards

**Comment by sajjad2923** [comment]
give folder path but dont create folder where you want to put your file. e.g
file path: D:\PhD 2nd Semester\Environmental Hydrology\Toolbox\pymetric-master\output
Out put would be directory where files would be saved but don't make output folder just give name in link.
